#!/usr/bin/env bash
# This script displays "Best School" 10 times with a 9th iteration hi with the while loop command
count=1
while [ $count -le 10 ]; do
     if [ $count -eq 9 ]; then
         echo "Best School"
         echo "Hi"
     else
          echo "Best School"
     fi
     count=$((count + 1))
done
