#!/usr/bin/env bash
#bash script to manage 'manage_my_process'
if [ "$1" == "start" ]; then
    ./manage_my_process &
    echo $$ > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "$1" == "stop" ]; then
    pkill -f ./manage_my_process
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
elif [ "$1" == "restart" ]; then
    pkill -f ./manage_my_process
    sudo rm /var/run/my_process.pid
    ./manage_my_process &
    echo $$ > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi

#!/usr/bin/env bash
#bash script that writes 'I am alive!' indefinitely to 'my_process' file
while ((1)); do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
done
